name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build, Test Push Docker Image and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (Optional) 
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/nodejs-app
          docker build -t $IMAGE:${{ github.sha }} .
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest

      - name: Push Docker images
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/nodejs-app
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      - name: Done
        run: echo "Docker image built and pushed successfully!"
        
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
            docker stop myapp || true && docker rm myapp || true
            docker run -d --name myapp -p 3033:3033 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest 
    


